### ISSUE TITLE
fbx.system.reboot() ==> freepybox.exceptions.HttpRequestError: insufficient_rights

### ISSUE THREAD

**Issue by lboue** [fstercq/freepybox#7]
Hello, I am trying to reboot my FreeboxV6 why this command:
`fbx.system.reboot()`

And I am getting the following error: `insufficient_rights`.

**Details:**
```
pi@raspberrypi:~/freepybox $ python3 freeboxV6-reboot.py 
Traceback (most recent call last):
  File "freeboxV6-reboot.py", line 23, in <module>
    fbx.system.reboot()
  File "/home/pi/freepybox/freepybox/api/system.py", line 18, in reboot
    self._access.post('system/reboot')
  File "/home/pi/freepybox/freepybox/access.py", line 39, in post
    raise HttpRequestError(resp['error_code'])
freepybox.exceptions.HttpRequestError: insufficient_rights
```
It seems that requested rights allowed to this app are not sufficient for reboot.
I had to edit **freebox** application permission to allow 'edit Freebox settings':

![modif_droits_appli_reboot](https://user-images.githubusercontent.com/938089/50047700-17d17c80-00bb-11e9-88c7-be91a5bb75ba.png)

Could you help me to fix that please?

Regards,

**Comment by lboue** [comment]
To help, here is the v6 API response for an [authorization method](http://mafreebox.freebox.fr/api/v6/authorization) call:

```
{
   "success":true,
   "result":[
      {
         "app_name":"Freebox Compagnon",
         "id":1,
         "app_version":"42",
         "device_name":"Phone",
         "last_session":1544811452,
         "req_ip":"192.168.1.101",
         "req_date":1543006529,
         "permissions":{
            "contacts":true,
            "downloader":true,
            "parental":false,
            "calls":true,
            "explorer":true,
            "pvr":true,
            "tv":true,
            "settings":true
         },
         "app_id":"fr.freebox.compagnon",
         "token_validity":"granted"
      },
      {
         "app_name":"freepybox",
         "id":6,
         "app_version":"",
         "device_name":"raspberrypi",
         "last_session":1544641640,
         "req_ip":"192.168.1.100",
         "req_date":1544905277,
         "permissions":{
            "parental":false,
            "explorer":true,
            "contacts":true,
            "tv":true,
            "downloader":true,
            "settings":false,
            "calls":true,
            "camera":false,
            "pvr":true,
            "home":false,
            "player":false
         },
         "app_id":"fpbx",
         "token_validity":"granted"
      }
   ]
}
```

Regards,

**Comment by stilllman** [comment]
I had the same issue when trying to switch wifi on/off ; I looked in the sdk documentation, but from what I can tell, there is no way to specify a list of requested rights when registering an application, so I'm not sure there is a solution to this issue.

**Comment by lboue** [comment]
I dont' have the v6 API documentation but I think it can work as following:
1) Ask for 'administrator' password
2) Get the account list `api/v6/authorization ` and find the id for the `"app_name":"freepybox"`
2) Change privileges for the with the authorization method `PUT /api/v6/authorization/6`

I think the are doing that for the official "Freebox" mobile  app.

![img_1349](https://user-images.githubusercontent.com/938089/50051010-aff65280-0109-11e9-9a57-5c2298175725.PNG)

Regards,
